README.MD
I don't think image path editing is the concern of this module, and should be handled by third party modules. Resolves #3
Text is copied from the readme of react-native-view-shot
=> Added information about how to save to file

android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.java
=> Added MultiLine text support for Android

README.MD, android/src/main/java/com/jimmydaddy/imagemarker/Utils.java, example/markerExample/App.js, example/markerExample/ios/Podfile, example/markerExample/ios/Podfile.lock, example/markerExample/ios/markerExample.xcodeproj/project.pbxproj, example/markerExample/ios/markerExample.xcodeproj/xcshareddata/xcschemes/markerExample.xcscheme, ios/RCTImageMarker/RCTImageMarker.m
=> feat: color support alpha fix #61

example/ios/Podfile.lock, ios/RCTImageMarker/Options.m, ios/RCTImageMarker/RCTImageMarker.m, ios/RCTImageMarker/TextBackground.m, ios/RCTImageMarker/Utils.h, ios/RCTImageMarker/Utils.m
=> fix: app crash on markText using iOS fix #105

CHANGELOG.md, README.MD, package.json
=> doc: docs for 1.0.0 sample

README.MD, src/index.ts
=> doc: docs for 1.0.0 complete

README.MD, android/gradle.properties, docs/latest/classes/Marker.html, docs/latest/enums/ImageFormat.html, docs/latest/enums/Position.html, docs/latest/enums/TextBackgroundType.html, docs/latest/index.html, docs/latest/interfaces/ImageMarkOptions.html, docs/latest/interfaces/ImageOptions.html, docs/latest/interfaces/PositionOptions.html, docs/latest/interfaces/ShadowLayerStyle.html, docs/latest/interfaces/TextBackgroundStyle.html, docs/latest/interfaces/TextMarkOptions.html, docs/latest/interfaces/TextOptions.html, docs/latest/interfaces/TextStyle.html, docs/latest/interfaces/WatermarkImageOptions.html, example/android/build.gradle, example/ios/Podfile.lock
=> fix: android api level compatible setting and docs

CHANGELOG.md, android/src/main/java/com/jimmydaddy/imagemarker/base/TextOptions.kt, example/src/App.tsx, package.json
=> fix:  textAlignment not uniform in android-ios,  fixed #119

README.MD
=> chore: update README.MD

.github/workflows/jekyll-gh-pages.yml, tsconfig.json
=> chore: test gh deploy actions

README.MD, docs/custom.css, docs/latest/assets/custom.css, tsconfig.json
=> chore: update readme

.github/release-drafter.yml, README.MD, android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/Constants.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/ImageOptions.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/MarkImageOptions.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/MarkerInsets.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/Options.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/Padding.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/TextBackgroundStyle.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/TextOptions.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/Utils.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/WatermarkImageOptions.kt, example/src/App.tsx, ios/RCTImageMarker/Constants.swift, ios/RCTImageMarker/ImageMarker.swift, ios/RCTImageMarker/ImageOptions.swift, ios/RCTImageMarker/MarkImageOptions.swift, ios/RCTImageMarker/MarkTextOptions.swift, ios/RCTImageMarker/Options.swift, ios/RCTImageMarker/Padding.swift, ios/RCTImageMarker/RCTConvert+ImageMarker.swift, ios/RCTImageMarker/TextBackground.swift, ios/RCTImageMarker/TextOptions.swift, ios/RCTImageMarker/TextStyle.swift, ios/RCTImageMarker/Utils.swift, ios/RCTImageMarker/WatermarkImageOptions.swift, package.json, src/index.ts, tsconfig.json
=> feat: more style options

CHANGELOG.md, package.json, tsconfig.doc.json, tsconfig.json
=> chore: release 1.1.3

CHANGELOG.md, README.MD, package.json, src/index.ts
=> chore: release 1.1.4

.github/workflows/jekyll-gh-pages-build.yml, .github/workflows/jekyll-gh-pages-deploy.yml, CHANGELOG.md, package.json
=> chore: update gh actions

CHANGELOG.md, package.json
=> chore: release 1.1.5

.github/workflows/jekyll-gh-pages-build.yml, README.MD, android/src/main/java/com/jimmydaddy/imagemarker/ImageLoader.kt, android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/MarkImageOptions.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/Options.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/Padding.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/TextStyle.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/WatermarkImageOptions.kt, example/android/build.gradle, example/ios/Podfile.lock, ios/RCTImageMarker/Constants.swift, ios/RCTImageMarker/MarkTextOptions.swift, src/index.ts
=> fix: fix #143 & document

CHANGELOG.md, android/src/main/java/com/jimmydaddy/imagemarker/base/TextOptions.kt, package.json
=> fix: fix android text rotation fix #156

README.MD, android/src/main/java/com/jimmydaddy/imagemarker/ImageLoader.kt, android/src/main/java/com/jimmydaddy/imagemarker/ImageProcess.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/Constants.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/ImageOptions.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/RNImageSRC.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/SaveFormat.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/TextBackgroundStyle.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/TextOptions.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/TextStyle.kt, example/ios/ImageMarkerExample/Info.plist, example/ios/Podfile.lock, example/package.json, example/src/App.tsx, src/index.ts
=> fix:  fix #158 android release bug  style not working

ios/RCTImageMarker/Utils.swift
=> fix: parse hex color string crash on iOS

CHANGELOG.md, example/ios/Podfile.lock, example/package.json, example/patches/react-native+0.71.11.patch, ios/RCTImageMarker/ImageMarker.swift, ios/RCTImageMarker/Utils.swift, package.json
=> fix: 1.1.x iOS crash and icon watermark not shown correctly

.github/workflows/ci.yml, android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.kt
AND 
fix: refactor image marker name generation
=> ci: use concurrency for gh workflow

.github/workflows/ci.yml, android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.kt
AND
fix: refactor image marker name generation
=> Ci: update gh workflow ci 1.1.x

android/src/main/java/com/jimmydaddy/imagemarker/base/TextOptions.kt
Fix fonts Watermark text in android
=> fix font (android)

.github/workflows/ci.yml, CHANGELOG.md, android/src/main/java/com/jimmydaddy/imagemarker/base/TextOptions.kt, android/src/main/java/com/jimmydaddy/imagemarker/base/TextStyle.kt, example/src/App.tsx, ios/RCTImageMarker/TextOptions.swift, ios/RCTImageMarker/TextStyle.swift, package.json, src/index.ts
=> fix: fix #202 generates inconsistent text size across different devices
